### ISSUE TITLE
reduce "states"

### ISSUE THREAD

**Issue by RaHehl** [mk-maddin/wattpilot-HA#45]
I try to reduce my HA Database size, following this guide: https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795

By checking my Database i see "sensor.wattpilot_charging_energy" is "consuming" 21% of the Tablespace by a total of 1284 entities 

Is there a option to reduce the "resolution" or "frequenz" ?

![image](https://github.com/mk-maddin/wattpilot-HA/assets/7577984/e3421531-678d-4b35-9915-bd2ae237a637)

**Comment by mk-maddin** [comment]
well within the integration - not if the integration is not fully re-programmed from "local push" to "local pull" mode.
Never the less within HA this is technically using a trigger based template sensor as history sensor which pulls the data from the real sensor only ever x seconds/minutes/hours/days etc. whatever.

Independently of this- can you for my own interest please explain for which scenario it is necessary to store the sensor historically so you are able to tell "on date x at time x my wattpilot charged with an power of x KWh", but don't mind if that data is only available every e.g. full minute instead of the exact timestamp you are asking for?

**Comment by RaHehl** [comment]
github template is named "Bug report" i wouldn't call my actual request a bug, that's why i've not used the bug template

**What version of Home Assistant Core is installed**
2024.5.5

**What version of Wattpilot integration is installed**
v0.2.1

**What version of Wattpilot are you using**
11KW

Scenario:

I've a PV Plant, Wattpilot, Heatpump, Bosch Energymanager, VW E-Golf


Most of the time this works quite well together, but it can happen that certain functions influence each other between using the PV electricity for excess charging of the car and excess use for the heat pump, e.g. for cooling

In the stupidest case, for example, a cloud combined with the excess charging of the car causes the surplus-controlled cooling to fail, so it can be useful to see what the energy flows were like at that point.

And for the energy dasboard, but I think the long-term statistics are stored differently?

**Comment by mk-maddin** [comment]
Then if it is not an isse or bug, but more like "how do I do X within HA" instead of a github Issue/Bug report maybe the HA forum or discord is the better place to ask :)

Thanks for your feedback - I understood your use case.
But how does it help in this case if at e.g. 15:21:23 seconds something influenced as you said - but the data your history contains is values just at 15:21:00 and 15:22:00?

In regards to the energy dashboard I am no expert on the way how things internally are stored within HA so I would once again highly recommend to ask that within the forum.-The only solution I am aware of is as described template sensor which pulls the data at your wanted frequency and store this within the history instead of the original sensor.

**Comment by RaHehl** [comment]
It's just a very specific question about this plugin, and you haven't left any information that you don't want to be bothered. 
With an unofficial custom component, I don't initially assume that the HA Discord is the first point of contact.
You could, for example, refer to discord in the Readme.md, so assuming that I have now understood you correctly

regarding your example: 15:21:00 and 15:22:00

I generally first asked what the options were, without specifying a target “frequency” in seconds.

The surplus functions of the heat pump and wattpilot also show a certain delay, so maybe 30sec or 60sec is actually enough for my use case

I actually saw the thing with the virtual sensor before the issue, but thought I'd ask because the amount of data supplied was noticeably high compared to other entities and components.
